import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-100 ">
        <form
          className="flex w-[22rem] flex-col gap-3 rounded-md  bg-white p-4 shadow-lg  sm:w-[550px]  "
          action=""
        >
          <span className="flex items-center justify-between">
            <span>Login</span>
            <input
              type="email"
              className="w-[70%] rounded-lg border border-red-700 p-1"
            />
          </span>
          <span className="flex items-center justify-between">
            <span>Password</span>
            <input
              type="password"
              className="w-[70%] rounded-lg border border-red-700 p-1"
            />
          </span>
        </form>
      </main>
    </>
  );
};

export default Home;
