import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-100 ">
        <form
          className="flex flex-col rounded-md border border-red-900 bg-white  shadow-lg  "
          action=""
        >
          <span className="flex">
            <span>Login</span>
            <input type="email" className="w-full border-red-700 border" />
          </span>
          <span className="flex">
            <span>Password</span>
            <input type="password" className="w-full border-red-700 border"/>
          </span>
        </form>
      </main>
    </>
  );
};

export default Home;
