import { type NextPage } from "next";
import Head from "next/head";
import LoginBtn from "~/components/LoginBtn";


const Home: NextPage = () => {
  // const app = express();

  // app.get("/", (req: Request, res: Response) => {
  //   console.log(req.query);
  //   res.send(200);
  // });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className="flex min-h-screen flex-col items-center justify-center bg-gray-100 ">
    
        <form
          className="flex w-[22rem] flex-col gap-3 rounded-md  bg-white p-4 shadow-lg  sm:w-[550px]  "
          action=""
        >
          <span className="flex items-center justify-between">
            <span>Login</span>
            <input
              type="email"
              className="w-[70%] rounded-lg border border-red-700 p-1"
            />
          </span>
          <span className="flex items-center justify-between">
            <span>Password</span>
            <input
              type="password"
              className="w-[70%] rounded-lg border border-red-700 p-1"
            />
          </span>
          <span className="mt-3 flex justify-center">
            <button className="rounded-xl bg-pink-400 px-4 py-2 transition-all hover:bg-pink-600">
              Sumbit
            </button>
          </span>
          <span className="flex items-center justify-center ">
            <a
              href="https://discord.com/api/oauth2/authorize?client_id=1093359624469630986&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fintroduction&response_type=code&scope=identify"
              className="rounded-xl bg-blue-300 px-4 py-2 transition-all hover:bg-blue-600"
            >
              Sign In
            </a>
          </span>
        </form>
      </main> */}
      <LoginBtn/>
    </>
  );
};

export default Home;
